# fly.toml app configuration file generated for host-ing on 2025-10-28T15:50:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'host-ing'
primary_region = 'iad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
